const students = [
  {
    id: 1,
    firstName: "oreoluwa",
    lastName: "fatomilola",
    level: "ss1",
    emailadd: "vfatomilola@ymail.com",
    image: "/static/media/OREOLUWA.d90b67d4.jpg",
  },
  {
    id: 2,
    firstName: "chinasaa",
    lastName: "dukor",
    level: "ss1",
    emailadd: "skoskoduks2@gmail.com",
    image: "/static/media/Dukor.d90b67d4.jpg",
  },
  {
    id: 3,
    firstName: "tony",
    lastName: "awugosi",
    level: "ss3",
    emailadd: "gositony123@gmail.com",
    image: "/static/media/FANTA.d90b67d4.jpeg",
  },
  {
    id: 4,
    firstName: "chuka",
    lastName: "ogbonna",
    level: "ss2",
    emailadd: "davechuks06@gmail.com",
    image: "./students-images/CHUKA.jpeg",
  },
  {
    id: 5,
    firstName: "chisom",
    lastName: "awugosi",
    level: "ss3",
    emailadd: "awugosic2@gmail.com",
    image: "./students-images/CHISOM.jpeg",
  },
  {
    id: 6,
    firstName: "deborah",
    lastName: "baushe",
    level: "ss1",
    emailadd: "deborahbaushe2007@gmail.com",
    image: "./students-images/DEBORAH.jpeg",
  },
  {
    id: 7,
    firstName: "ebosetale",
    lastName: "ehebha",
    level: "ss1",
    emailadd: "ebosetalechebha@gmail.com",
    image: "./students-images/TALLY.jpg",
  },
  {
    id: 8,
    firstName: "michael",
    lastName: "mamman",
    level: "ss1",
    emailadd: "michaelmamman@gmail.com",
    image: "./students-images/COCACOLA.jpg",
  },
  {
    id: 9,
    firstName: "chidera",
    lastName: "okelu",
    level: "ss3",
    emailadd: "chideraokelu@gmail.com",
    image: "./students-images/",
  },
  {
    id: 10,
    firstName: "seyitan",
    lastName: "edwards",
    level: "ss3",
    emailadd: "seyitanedwards@gmail.com",
    image: "./students-images/EYITAN.jpeg",
  },
  {
    id: 11,
    firstName: "opemipo",
    lastName: "ashiru",
    level: "ss3",
    emailadd: "opeash234@gmail.com",
    image: "./students-images/",
  },
  {
    id: 12,
    firstName: "chizitahra",
    lastName: "murphy-uzohue",
    level: "ss2",
    emailadd: "chloemurphy217@gmail.com",
    image: "./students-images/zita.jpg",
  },
  {
    id: 13,
    firstName: "onyinyechi",
    lastName: "eleogu",
    level: "ss3",
    emailadd: "eleoguonyinyechi@gmail.com",
    image: "./students-images/ONYECHI.jpeg",
  },
  {
    id: 14,
    firstName: "sharon",
    lastName: "omotosho",
    level: "ss3",
    emailadd: "kanyinsharon@gmail.comm",
    image: "./students-images/sharon.jpeg",
  },
  {
    id: 15,
    firstName: "nnedoziem",
    lastName: "anike-nweze",
    level: "ss3",
    emailadd: "edoziemanikenweze@gmail.com",
    image: "./students-images/DOZIE.jpg",
  },
  {
    id: 16,
    firstName: "michael-daniel",
    lastName: "ana",
    level: "ss3",
    emailadd: "kingana108@gmail.com",
    image: "./students-images/MD.jpeg",
  },
  {
    id: 17,
    firstName: "arinze",
    lastName: "nwabineli",
    level: "ss3",
    emailadd: "arinzenwabineli1@icloud.com",
    image: "./students-images/arinze.jpeg",
  },
  {
    id: 18,
    firstName: "oselumese",
    lastName: "okorunwa",
    level: "ss3",
    emailadd: "oseoko4925@gmail.com",
    image: "./students-images/OSE.jpg",
  },
];

export default students;
